server:
  port : 8088

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: english_helper
      username: root
      password: example
      authentication-database: admin

# App Properties
english-helper:
  security:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000